---
- name: Ensure podman and java are installed
  ansible.builtin.dnf:
    name:
      - podman
      - java
    state: present

- name: Open Firewalld for Kafka
  ansible.posix.firewalld:
    port: 9092/tcp
    permanent: true
    state: enabled
  notify: Restart Firewalld

- name: Open Firewalld for ZooKeeper
  ansible.posix.firewalld:
    port: 2181/tcp
    permanent: true
    state: enabled
  notify: Restart Firewalld

- name: Force all notified handlers to run at this point
  ansible.builtin.meta: flush_handlers

- name: Ensure "messaging" network exists
  containers.podman.podman_network:
    name: messaging
    state: present

- name: Pull kafka and zookeeper images
  containers.podman.podman_image:
    name: "{{ item }}"
  loop:
    - docker.io/bitnami/zookeeper
    - docker.io/bitnami/kafka

- name: Deploy Zookeeper Service file
  ansible.builtin.template:
    src: templates/zookeeper.j2
    dest: /etc/systemd/system/container-zookeeper.service
    mode: "0644"
    group: root
    owner: root

- name: Start and enable ZooKeeper podman service
  ansible.builtin.service:
    name: container-zookeeper.service
    state: started
    enabled: true

- name: Deploy Kafka Service file
  ansible.builtin.template:
    src: templates/kafka.j2
    dest: /etc/systemd/system/container-kafka.service
    mode: "0644"
    group: root
    owner: root

- name: Start and enable Kafka podman service
  ansible.builtin.service:
    name: container-kafka.service
    state: started
    enabled: true

- name: Extract kafka tar
  ansible.builtin.unarchive:
    src: https://downloads.apache.org/kafka/3.9.0/kafka_2.13-3.9.0.tgz
    dest: /opt
    remote_src: true

- name: Create Kafka topic
  ansible.builtin.command: /opt/kafka_2.13-3.9.0/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic {{ topic
    }}
  register: kafkatopic
  changed_when: kafkatopic.stdout == "Created topic " ~ topic ~ "."
  failed_when:
    - '"already exists" not in kafkatopic.stderr'
    - kafkatopic.stdout != "Created topic " ~ topic ~ "."
  tags:
    - createtopic
